
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: libra-storage-class
provisioner: kubernetes.io/gce-pd # TODO: aws?
parameters:
  type: pd-standard
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate

